# fly.toml file generated for cb5-research-api

app = "cb5-research-api"
primary_region = "sjc"

[build]

[env]
  API_HOST = "0.0.0.0"
  API_RELOAD = "false"
  LOG_LEVEL = "info"
  ENVIRONMENT = "production"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256