[build]
builder = "nixpacks"

[deploy]
startCommand = "python start.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
API_HOST = "0.0.0.0"
API_PORT = "$PORT"
API_RELOAD = "false"
LOG_LEVEL = "info"
ENVIRONMENT = "production"